### ISSUE TITLE
如何生成背景透明BMP 

### ISSUE THREAD

**Issue by MyNameIsKai** [hmgle/dot_matrix_font_to_bmp#3]
我使用 ./text2bmp -g 0xfff0 -f 0x0 -c 2 -u 16 -d 8 -l 16 -r 8 -i 8 test3.txt > test3.bmp 生成的不是透明的

**Comment by hmgle** [comment]
你好。
我查了下 [bmp 格式](https://en.wikipedia.org/wiki/BMP_file_format) 的文档，32 位的是支持透明的，而我写的这个只支持 24 位和 16 位，因此还不支持透明背景。
