### ISSUE TITLE
使用“make”指令做编译是遇到ERROR

### ISSUE THREAD

**Issue by MokhaLeee** [hmgle/dot_matrix_font_to_bmp#5]
大佬好，我在尝试用make 或者make all指令编译obj的时候系统总是在报错。
我是用的Win10下用Msys2来编译的。另外我也尝试了一下cMake，同样会报错下属指令，不知道该如何处理：

![image](https://user-images.githubusercontent.com/89029102/137874564-879eb543-2445-469c-a2f7-4dcf67e39daf.png)

**Comment by hmgle** [comment]
@MokhaLeee 更新了，可以再试试。

**Comment by MokhaLeee** [comment]
非常感谢
